<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ciies = [
            ['state_id' => 1,'name' => 'Bhimbar'],
            ['state_id' => 1,'name' => 'Kotli'],
            ['state_id' => 1,'name' => 'Kotli District'],
            ['state_id' => 1,'name' => 'Mirpur District'],
            ['state_id' => 1,'name' => 'Muzaffarabad'],
            ['state_id' => 1,'name' => 'New Mirpur'],
            ['state_id' => 1,'name' => 'Rawala Kot'],
            ['state_id' => 2,'name' => 'Alik Ghund'],
            ['state_id' => 2,'name' => 'Awaran District'],
            ['state_id' => 2,'name' => 'Barkhan'],
            ['state_id' => 2,'name' => 'Bela'],
            ['state_id' => 2,'name' => 'Bhag'],
            ['state_id' => 2,'name' => 'Barkhan District'],
            ['state_id' => 2,'name' => 'Chaman'],
            ['state_id' => 2,'name' => 'Chowki Jamali'],
            ['state_id' => 2,'name' => 'Chagai District'],
            ['state_id' => 2,'name' => 'Dadhar'],
            ['state_id' => 2,'name' => 'Dalbandin'],
            ['state_id' => 2,'name' => 'Dera Bugti'],
            ['state_id' => 2,'name' => 'Dera Bugti District'],
            ['state_id' => 2,'name' => 'Duki'],
            ['state_id' => 2,'name' => 'Gadani'],
            ['state_id' => 2,'name' => 'Garhi Khairo'],
            ['state_id' => 2,'name' => 'Gwadar'],
            ['state_id' => 2,'name' => 'Harnai'],
            ['state_id' => 2,'name' => 'Jhal Magsi District'],
            ['state_id' => 2,'name' => 'Jiwani'],
            ['state_id' => 2,'name' => 'Jafarabad District'],
            ['state_id' => 2,'name' => 'Kalat'],
            ['state_id' => 2,'name' => 'Kalat District'],
            ['state_id' => 2,'name' => 'Khadan Khak'],
            ['state_id' => 2,'name' => 'Kharan'],
            ['state_id' => 2,'name' => 'Khuzdar'],
            ['state_id' => 2,'name' => 'Khuzdar District'],
            ['state_id' => 2,'name' => 'Kharan District'],
            ['state_id' => 2,'name' => 'Kohlu'],
            ['state_id' => 2,'name' => 'Kot Malik Barkhurdar'],
            ['state_id' => 2,'name' => 'Lasbela District'],
            ['state_id' => 2,'name' => 'Loralai'],
            ['state_id' => 2,'name' => 'Loralai District'],
            ['state_id' => 2,'name' => 'Mach'],
            ['state_id' => 2,'name' => 'Mastung'],
            ['state_id' => 2,'name' => 'Mastung District'],
            ['state_id' => 2,'name' => 'Mehrabpur'],
            ['state_id' => 2,'name' => 'Mūsa Khel District'],
            ['state_id' => 2,'name' => 'Nasīrabad District'],
            ['state_id' => 2,'name' => 'Nushki'],
            ['state_id' => 2,'name' => 'Ormara'],
            ['state_id' => 2,'name' => 'Panjgūr District'],
            ['state_id' => 2,'name' => 'Pasni'],
            ['state_id' => 2,'name' => 'Pishin'],
            ['state_id' => 2,'name' => 'Qila Saifullah District'],
            ['state_id' => 2,'name' => 'Quetta'],
            ['state_id' => 2,'name' => 'Quetta District'],
            ['state_id' => 2,'name' => 'Sibi'],
            ['state_id' => 2,'name' => 'Sohbatpur'],
            ['state_id' => 2,'name' => 'Surab'],
            ['state_id' => 2,'name' => 'Turbat'],
            ['state_id' => 2,'name' => 'Usta Muhammad'],
            ['state_id' => 2,'name' => 'Uthal'],
            ['state_id' => 2,'name' => 'Zhob'],
            ['state_id' => 2,'name' => 'Zhob District'],
            ['state_id' => 2,'name' => 'Ziarat'],
            ['state_id' => 2,'name' => 'Ziarat District'],
            ['state_id' => 3,'name' => 'Alizai'],
            ['state_id' => 3,'name' => 'Gulishah Kach'],
            ['state_id' => 3,'name' => 'Landi Kotal'],
            ['state_id' => 3,'name' => 'Miran Shah'],
            ['state_id' => 3,'name' => 'North Wazīristan Agency'],
            ['state_id' => 3,'name' => 'Shinpokh'],
            ['state_id' => 3,'name' => 'South Wazīristan Agency'],
            ['state_id' => 3,'name' => 'Wana'],
            ['state_id' => 4,'name' => 'Barishal'],
            ['state_id' => 4,'name' => 'Gilgit'],
            ['state_id' => 4,'name' => 'Skardu'],
            ['state_id' => 5,'name' => 'Islamabad'],
            ['state_id' => 6,'name' => 'Abbottabad'],
            ['state_id' => 6,'name' => 'Akora'],
            ['state_id' => 6,'name' => 'Aman Garh'],
            ['state_id' => 6,'name' => 'Amirabad'],
            ['state_id' => 6,'name' => 'Ashanagro Koto'],
            ['state_id' => 6,'name' => 'Baffa'],
            ['state_id' => 6,'name' => 'Bannu'],
            ['state_id' => 6,'name' => 'Bat Khela'],
            ['state_id' => 6,'name' => 'Battagram'],
            ['state_id' => 6,'name' => 'Battagram District'],
            ['state_id' => 6,'name' => 'Buner District'],
            ['state_id' => 6,'name' => 'Charsadda'],
            ['state_id' => 6,'name' => 'Cherat Cantonement'],
            ['state_id' => 6,'name' => 'Chitral'],
            ['state_id' => 6,'name' => 'Dera Ismail Khan'],
            ['state_id' => 6,'name' => 'Dera Ismaīl Khan District'],
            ['state_id' => 6,'name' => 'Doaba'],
            ['state_id' => 6,'name' => 'Hangu'],
            ['state_id' => 6,'name' => 'Haripur'],
            ['state_id' => 6,'name' => 'Havelian'],
            ['state_id' => 6,'name' => 'Kakad Wari Dir Upper'],
            ['state_id' => 6,'name' => 'Karak'],
            ['state_id' => 6,'name' => 'Khalabat'],
            ['state_id' => 6,'name' => 'Kohat'],
            ['state_id' => 6,'name' => 'Kulachi'],
            ['state_id' => 6,'name' => 'Lachi'],
            ['state_id' => 6,'name' => 'Lakki'],
            ['state_id' => 6,'name' => 'Mansehra'],
            ['state_id' => 6,'name' => 'Mardan'],
            ['state_id' => 6,'name' => 'Mingora'],
            ['state_id' => 6,'name' => 'Noorabad'],
            ['state_id' => 6,'name' => 'Nowshera'],
            ['state_id' => 6,'name' => 'Nowshera Cantonment'],
            ['state_id' => 6,'name' => 'Pabbi'],
            ['state_id' => 6,'name' => 'Paharpur'],
            ['state_id' => 6,'name' => 'Peshawar'],
            ['state_id' => 6,'name' => 'Risalpur Cantonment'],
            ['state_id' => 6,'name' => 'Sarai Naurang'],
            ['state_id' => 6,'name' => 'Shabqadar'],
            ['state_id' => 6,'name' => 'Shingli Bala'],
            ['state_id' => 6,'name' => 'Shorkot'],
            ['state_id' => 6,'name' => 'Swabi'],
            ['state_id' => 6,'name' => 'Tangi'],
            ['state_id' => 6,'name' => 'Tank'],
            ['state_id' => 6,'name' => 'Thal'],
            ['state_id' => 6,'name' => 'Topi'],
            ['state_id' => 6,'name' => 'Upper Dir'],
            ['state_id' => 6,'name' => 'Utmanzai'],
            ['state_id' => 6,'name' => 'Zaida'],
            ['state_id' => 7,'name' => 'Ahmedpur East'],
            ['state_id' => 7,'name' => 'Ahmadpur Sial'],
            ['state_id' => 7,'name' => 'Alipur Chatha'],
            ['state_id' => 7,'name' => 'Arifwala'],
            ['state_id' => 7,'name' => 'Attock Tehsil'],
            ['state_id' => 7,'name' => 'Baddomalhi'],
            ['state_id' => 7,'name' => 'Bahawalnagar'],
            ['state_id' => 7,'name' => 'Bahawalpur'],
            ['state_id' => 7,'name' => 'Bakhri Ahmad Khan'],
            ['state_id' => 7,'name' => 'Basirpur'],
            ['state_id' => 7,'name' => 'Basti Dosa'],
            ['state_id' => 7,'name' => 'Begowala'],
            ['state_id' => 7,'name' => 'Bhakkar'],
            ['state_id' => 7,'name' => 'Bhalwal'],
            ['state_id' => 7,'name' => 'Bhawana'],
            ['state_id' => 7,'name' => 'Bhera'],
            ['state_id' => 7,'name' => 'Bhopalwala'],
            ['state_id' => 7,'name' => 'Burewala'],
            ['state_id' => 7,'name' => 'Chak Azam Saffo'],
            ['state_id' => 7,'name' => 'Chak Jhumra'],
            ['state_id' => 7,'name' => 'Chak One Hundred Twenty Nine Left'],
            ['state_id' => 7,'name' => 'Chak Thirty-one -Eleven Left'],
            ['state_id' => 7,'name' => 'Chak Two Hundred Forty-Nine TDA'],
            ['state_id' => 7,'name' => 'Chakwal'],
            ['state_id' => 7,'name' => 'Chawinda'],
            ['state_id' => 7,'name' => 'Rabwah'],
            ['state_id' => 7,'name' => 'Chichawatni'],
            ['state_id' => 7,'name' => 'Chiniot'],
            ['state_id' => 7,'name' => 'Chishtian'],
            ['state_id' => 7,'name' => 'Choa Saidanshah'],
            ['state_id' => 7,'name' => 'Chunian'],
            ['state_id' => 7,'name' => 'Daira Din Panah'],
            ['state_id' => 7,'name' => 'Dajal'],
            ['state_id' => 7,'name' => 'Dandot RS'],
            ['state_id' => 7,'name' => 'Darya Khan'],
            ['state_id' => 7,'name' => 'Daska'],
            ['state_id' => 7,'name' => 'Daultala'],
            ['state_id' => 7,'name' => 'Dera Ghazi Khan'],
            ['state_id' => 7,'name' => 'Dhanot'],
            ['state_id' => 7,'name' => 'Dhaunkal'],
            ['state_id' => 7,'name' => 'Dijkot'],
            ['state_id' => 7,'name' => 'Dinan Bashnoian Wala'],
            ['state_id' => 7,'name' => 'Dinga'],
            ['state_id' => 7,'name' => 'Dipalpur'],
            ['state_id' => 7,'name' => 'Dullewala'],
            ['state_id' => 7,'name' => 'Dunga Bunga'],
            ['state_id' => 7,'name' => 'Dunyapur'],
            ['state_id' => 7,'name' => 'Eminabad'],
            ['state_id' => 7,'name' => 'Faisalabad'],
            ['state_id' => 7,'name' => 'Faqirwali'],
            ['state_id' => 7,'name' => 'Faruka'],
            ['state_id' => 7,'name' => 'Fazilpur'],
            ['state_id' => 7,'name' => 'Fort Abbas'],
            ['state_id' => 7,'name' => 'Garh Maharaja'],
            ['state_id' => 7,'name' => 'Gojra'],
            ['state_id' => 7,'name' => 'Gujar Khan'],
            ['state_id' => 7,'name' => 'Gujranwala'],
            ['state_id' => 7,'name' => 'Gujrat'],
            ['state_id' => 7,'name' => 'Hadali'],
            ['state_id' => 7,'name' => 'Hafizabad'],
            ['state_id' => 7,'name' => 'Harnoli'],
            ['state_id' => 7,'name' => 'Harunabad'],
            ['state_id' => 7,'name' => 'Hasilpur'],
            ['state_id' => 7,'name' => 'Haveli Lakha'],
            ['state_id' => 7,'name' => 'Hazro'],
            ['state_id' => 7,'name' => 'Hujra Shah Muqeem'],
            ['state_id' => 7,'name' => 'Jahanian Shah'],
            ['state_id' => 7,'name' => 'Jalalpur Jattan'],
            ['state_id' => 7,'name' => 'Jalalpur Pirwala'],
            ['state_id' => 7,'name' => 'Jampur'],
            ['state_id' => 7,'name' => 'Jand'],
            ['state_id' => 7,'name' => 'Jandiala Sher Khan'],
            ['state_id' => 7,'name' => 'Jaranwala'],
            ['state_id' => 7,'name' => 'Jatoi Shimali'],
            ['state_id' => 7,'name' => 'Jauharabad'],
            ['state_id' => 7,'name' => 'Jhang'],
            ['state_id' => 7,'name' => 'Jhang Sadar'],
            ['state_id' => 7,'name' => 'Jhawarian'],
            ['state_id' => 7,'name' => 'Jhelum'],
            ['state_id' => 7,'name' => 'Kabirwala'],
            ['state_id' => 7,'name' => 'Kahna Nau'],
            ['state_id' => 7,'name' => 'Kahuta'],
            ['state_id' => 7,'name' => 'Kalabagh'],
            ['state_id' => 7,'name' => 'Kalaswala'],
            ['state_id' => 7,'name' => 'Kaleke Mandi'],
            ['state_id' => 7,'name' => 'Kallar Kahar'],
            ['state_id' => 7,'name' => 'Kalur Kot'],
            ['state_id' => 7,'name' => 'Kamalia'],
            ['state_id' => 7,'name' => 'Kamar Mushani'],
            ['state_id' => 7,'name' => 'Kamoke'],
            ['state_id' => 7,'name' => 'Kamra'],
            ['state_id' => 7,'name' => 'Kanganpur'],
            ['state_id' => 7,'name' => 'Karor'],
            ['state_id' => 7,'name' => 'Kasur'],
            ['state_id' => 7,'name' => 'Keshupur'],
            ['state_id' => 7,'name' => 'Khairpur Tamiwali'],
            ['state_id' => 7,'name' => 'Khandowa'],
            ['state_id' => 7,'name' => 'Khanewal'],
            ['state_id' => 7,'name' => 'Khanga Dogran'],
            ['state_id' => 7,'name' => 'Khangarh'],
            ['state_id' => 7,'name' => 'Khanpur'],
            ['state_id' => 7,'name' => 'Kharian'],
            ['state_id' => 7,'name' => 'Khewra'],
            ['state_id' => 7,'name' => 'Khurrianwala'],
            ['state_id' => 7,'name' => 'Khushab'],
            ['state_id' => 7,'name' => 'Kot Addu Tehsil'],
            ['state_id' => 7,'name' => 'Kot Ghulam Muhammad'],
            ['state_id' => 7,'name' => 'Kot Mumin'],
            ['state_id' => 7,'name' => 'Kot Radha Kishan'],
            ['state_id' => 7,'name' => 'Kot Rajkour'],
            ['state_id' => 7,'name' => 'Kot Samaba'],
            ['state_id' => 7,'name' => 'Kot Sultan'],
            ['state_id' => 7,'name' => 'Kotli Loharan'],
            ['state_id' => 7,'name' => 'Kundian'],
            ['state_id' => 7,'name' => 'Kunjah'],
            ['state_id' => 7,'name' => 'Ladhewala Waraich'],
            ['state_id' => 7,'name' => 'Lahore'],
            ['state_id' => 7,'name' => 'Lala Musa'],
            ['state_id' => 7,'name' => 'Lalian'],
            ['state_id' => 7,'name' => 'Layyah'],
            ['state_id' => 7,'name' => 'Layyah District'],
            ['state_id' => 7,'name' => 'Liliani'],
            ['state_id' => 7,'name' => 'Lodhran'],
            ['state_id' => 7,'name' => 'Mailsi'],
            ['state_id' => 7,'name' => 'Malakwal'],
            ['state_id' => 7,'name' => 'Malakwal City'],
            ['state_id' => 7,'name' => 'Mamu Kanjan'],
            ['state_id' => 7,'name' => 'Mananwala'],
            ['state_id' => 7,'name' => 'Mandi Bahauddin'],
            ['state_id' => 7,'name' => 'Mangla'],
            ['state_id' => 7,'name' => 'Mankera'],
            ['state_id' => 7,'name' => 'Mehmand Chak'],
            ['state_id' => 7,'name' => 'Mian Channun'],
            ['state_id' => 7,'name' => 'Mianke Mor'],
            ['state_id' => 7,'name' => 'Mianwali'],
            ['state_id' => 7,'name' => 'Minchinabad'],
            ['state_id' => 7,'name' => 'Mitha Tiwana'],
            ['state_id' => 7,'name' => 'Moza Shahwala'],
            ['state_id' => 7,'name' => 'Multan'],
            ['state_id' => 7,'name' => 'Muridke'],
            ['state_id' => 7,'name' => 'Murree'],
            ['state_id' => 7,'name' => 'Mustafabad'],
            ['state_id' => 7,'name' => 'Muzaffargarh'],
            ['state_id' => 7,'name' => 'Nankana Sahib'],
            ['state_id' => 7,'name' => 'Narang Mandi'],
            ['state_id' => 7,'name' => 'Narowal'],
            ['state_id' => 7,'name' => 'Naushahra Virkan'],
            ['state_id' => 7,'name' => 'Nazir Town'],
            ['state_id' => 7,'name' => 'Okara'],
            ['state_id' => 7,'name' => 'Pakpattan'],
            ['state_id' => 7,'name' => 'Pasrur'],
            ['state_id' => 7,'name' => 'Pattoki'],
            ['state_id' => 7,'name' => 'Phalia'],
            ['state_id' => 7,'name' => 'Pind Dadan Khan'],
            ['state_id' => 7,'name' => 'Pindi Bhattian'],
            ['state_id' => 7,'name' => 'Pindi Gheb'],
            ['state_id' => 7,'name' => 'Pir Mahal'],
            ['state_id' => 7,'name' => 'Qadirpur Ran'],
            ['state_id' => 7,'name' => 'Rahim Yar Khan'],
            ['state_id' => 7,'name' => 'Raiwind'],
            ['state_id' => 7,'name' => 'Raja Jang'],
            ['state_id' => 7,'name' => 'Rajanpur'],
            ['state_id' => 7,'name' => 'Rasulnagar'],
            ['state_id' => 7,'name' => 'Rawalpindi'],
            ['state_id' => 7,'name' => 'Rawalpindi District'],
            ['state_id' => 7,'name' => 'Renala Khurd'],
            ['state_id' => 7,'name' => 'Rojhan'],
            ['state_id' => 7,'name' => 'Sadiqabad'],
            ['state_id' => 7,'name' => 'Sahiwal'],
            ['state_id' => 7,'name' => 'Sambrial'],
            ['state_id' => 7,'name' => 'Sangla Hill'],
            ['state_id' => 7,'name' => 'Sanjwal'],
            ['state_id' => 7,'name' => 'Sarai Alamgir'],
            ['state_id' => 7,'name' => 'Sarai Sidhu'],
            ['state_id' => 7,'name' => 'Sargodha'],
            ['state_id' => 7,'name' => 'Shorkot'],
            ['state_id' => 7,'name' => 'Shahpur'],
            ['state_id' => 7,'name' => 'Shahr Sultan'],
            ['state_id' => 7,'name' => 'Shakargarh'],
            ['state_id' => 7,'name' => 'Sharqpur'],
            ['state_id' => 7,'name' => 'Sheikhupura'],
            ['state_id' => 7,'name' => 'Shujaabad'],
            ['state_id' => 7,'name' => 'Sialkot'],
            ['state_id' => 7,'name' => 'Sillanwali'],
            ['state_id' => 7,'name' => 'Sodhra'],
            ['state_id' => 7,'name' => 'Sukheke Mandi'],
            ['state_id' => 7,'name' => 'Surkhpur'],
            ['state_id' => 7,'name' => 'Talagang'],
            ['state_id' => 7,'name' => 'Talamba'],
            ['state_id' => 7,'name' => 'Tandlianwala'],
            ['state_id' => 7,'name' => 'Taunsa'],
            ['state_id' => 7,'name' => 'Toba Tek Singh'],
            ['state_id' => 7,'name' => 'Vihari'],
            ['state_id' => 7,'name' => 'Wazirabad'],
            ['state_id' => 7,'name' => 'Yazman'],
            ['state_id' => 7,'name' => 'Zafarwal'],
            ['state_id' => 7,'name' => 'Zahir Pir'],
            ['state_id' => 7,'name' => 'Chuhar Kana'],
            ['state_id' => 7,'name' => 'Dhok Awan'],
            ['state_id' => 7,'name' => 'Daud Khel'],
            ['state_id' => 7,'name' => 'Ferozewala'],
            ['state_id' => 7,'name' => 'Gujranwala Division'],
            ['state_id' => 7,'name' => 'Hasan Abdal'],
            ['state_id' => 7,'name' => 'Kohror Pakka'],
            ['state_id' => 7,'name' => 'Mandi Bahauddin District'],
            ['state_id' => 7,'name' => 'Multan District'],
            ['state_id' => 7,'name' => 'Pakki Shagwanwali'],
            ['state_id' => 7,'name' => 'Qila Didar Singh'],
            ['state_id' => 7,'name' => 'Rahimyar Khan District'],
            ['state_id' => 7,'name' => 'Shahkot Tehsil'],
            ['state_id' => 7,'name' => 'Umerkot'],
            ['state_id' => 7,'name' => 'Wah'],
            ['state_id' => 7,'name' => 'Warburton'],
            ['state_id' => 7,'name' => 'West Punjab'],
            ['state_id' => 8,'name' => 'Adilpur'],
            ['state_id' => 8,'name' => 'Badin'],
            ['state_id' => 8,'name' => 'Bagarji'],
            ['state_id' => 8,'name' => 'Bandhi'],
            ['state_id' => 8,'name' => 'Berani'],
            ['state_id' => 8,'name' => 'Bhan'],
            ['state_id' => 8,'name' => 'Bhiria'],
            ['state_id' => 8,'name' => 'Bhit Shah'],
            ['state_id' => 8,'name' => 'Bozdar Wada'],
            ['state_id' => 8,'name' => 'Bulri'],
            ['state_id' => 8,'name' => 'Chak'],
            ['state_id' => 8,'name' => 'Chamber'],
            ['state_id' => 8,'name' => 'Chhor'],
            ['state_id' => 8,'name' => 'Chuhar Jamali'],
            ['state_id' => 8,'name' => 'Dadu'],
            ['state_id' => 8,'name' => 'Daromehar'],
            ['state_id' => 8,'name' => 'Darya Khan Marri'],
            ['state_id' => 8,'name' => 'Daulatpur'],
            ['state_id' => 8,'name' => 'Daur'],
            ['state_id' => 8,'name' => 'Dhoro Naro'],
            ['state_id' => 8,'name' => 'Digri'],
            ['state_id' => 8,'name' => 'Diplo'],
            ['state_id' => 8,'name' => 'Dokri'],
            ['state_id' => 8,'name' => 'Gambat'],
            ['state_id' => 8,'name' => 'Garhiyasin'],
            ['state_id' => 8,'name' => 'Gharo'],
            ['state_id' => 8,'name' => 'Ghauspur'],
            ['state_id' => 8,'name' => 'Ghotki'],
            ['state_id' => 8,'name' => 'Goth Garelo'],
            ['state_id' => 8,'name' => 'Goth Phulji'],
            ['state_id' => 8,'name' => 'Goth Radhan'],
            ['state_id' => 8,'name' => 'Hala'],
            ['state_id' => 8,'name' => 'Hingorja'],
            ['state_id' => 8,'name' => 'Hyderabad'],
            ['state_id' => 8,'name' => 'Islamkot'],
            ['state_id' => 8,'name' => 'Jacobabad'],
            ['state_id' => 8,'name' => 'Jamshoro'],
            ['state_id' => 8,'name' => 'Jati'],
            ['state_id' => 8,'name' => 'Jhol'],
            ['state_id' => 8,'name' => 'Johi'],
            ['state_id' => 8,'name' => 'Jam Sahib'],
            ['state_id' => 8,'name' => 'Kadhan'],
            ['state_id' => 8,'name' => 'Kambar'],
            ['state_id' => 8,'name' => 'Kandhkot'],
            ['state_id' => 8,'name' => 'Kandiari'],
            ['state_id' => 8,'name' => 'Kandiaro'],
            ['state_id' => 8,'name' => 'Karachi'],
            ['state_id' => 8,'name' => 'Karaundi'],
            ['state_id' => 8,'name' => 'Kario Ghanwar'],
            ['state_id' => 8,'name' => 'Kashmor'],
            ['state_id' => 8,'name' => 'Keti Bandar'],
            ['state_id' => 8,'name' => 'Khadro'],
            ['state_id' => 8,'name' => 'Khairpur'],
            ['state_id' => 8,'name' => 'Khairpur Mir’s'],
            ['state_id' => 8,'name' => 'Khairpur Nathan Shah'],
            ['state_id' => 8,'name' => 'Khanpur Mahar'],
            ['state_id' => 8,'name' => 'Kot Diji'],
            ['state_id' => 8,'name' => 'Kotri'],
            ['state_id' => 8,'name' => 'Kunri'],
            ['state_id' => 8,'name' => 'Lakhi'],
            ['state_id' => 8,'name' => 'Larkana'],
            ['state_id' => 8,'name' => 'Madeji'],
            ['state_id' => 8,'name' => 'Malir Cantonment'],
            ['state_id' => 8,'name' => 'Matiari'],
            ['state_id' => 8,'name' => 'Matli'],
            ['state_id' => 8,'name' => 'Mehar'],
            ['state_id' => 8,'name' => 'Miro Khan'],
            ['state_id' => 8,'name' => 'Mirpur Bhtoro'],
            ['state_id' => 8,'name' => 'Mirpur Khas'],
            ['state_id' => 8,'name' => 'Mirpur Mathelo'],
            ['state_id' => 8,'name' => 'Mirpur Sakro'],
            ['state_id' => 8,'name' => 'Mirwah Gorchani'],
            ['state_id' => 8,'name' => 'Mithi'],
            ['state_id' => 8,'name' => 'Moro'],
            ['state_id' => 8,'name' => 'Nabisar'],
            ['state_id' => 8,'name' => 'Nasirabad'],
            ['state_id' => 8,'name' => 'Naudero'],
            ['state_id' => 8,'name' => 'Naukot'],
            ['state_id' => 8,'name' => 'Naushahro Firoz'],
            ['state_id' => 8,'name' => 'Nawabshah'],
            ['state_id' => 8,'name' => 'New Badah'],
            ['state_id' => 8,'name' => 'Pad Idan'],
            ['state_id' => 8,'name' => 'Pano Aqil'],
            ['state_id' => 8,'name' => 'Pir Jo Goth'],
            ['state_id' => 8,'name' => 'Pithoro'],
            ['state_id' => 8,'name' => 'Rajo Khanani'],
            ['state_id' => 8,'name' => 'Ranipur'],
            ['state_id' => 8,'name' => 'Ratodero'],
            ['state_id' => 8,'name' => 'Rohri'],
            ['state_id' => 8,'name' => 'Rustam'],
            ['state_id' => 8,'name' => 'Sakrand'],
            ['state_id' => 8,'name' => 'Samaro'],
            ['state_id' => 8,'name' => 'Sanghar'],
            ['state_id' => 8,'name' => 'Sann'],
            ['state_id' => 8,'name' => 'Sehwan'],
            ['state_id' => 8,'name' => 'Setharja Old'],
            ['state_id' => 8,'name' => 'Shahdad Kot'],
            ['state_id' => 8,'name' => 'Shahdadpur'],
            ['state_id' => 8,'name' => 'Shahpur Chakar'],
            ['state_id' => 8,'name' => 'Shikarpur'],
            ['state_id' => 8,'name' => 'Sinjhoro'],
            ['state_id' => 8,'name' => 'Sobhodero'],
            ['state_id' => 8,'name' => 'Sukkur'],
            ['state_id' => 8,'name' => 'Sīta Road'],
            ['state_id' => 8,'name' => 'Talhar'],
            ['state_id' => 8,'name' => 'Tando Adam'],
            ['state_id' => 8,'name' => 'Tando Allahyar'],
            ['state_id' => 8,'name' => 'Tando Bago'],
            ['state_id' => 8,'name' => 'Tando Jam'],
            ['state_id' => 8,'name' => 'Tando Mitha Khan'],
            ['state_id' => 8,'name' => 'Tando Muhammad Khan'],
            ['state_id' => 8,'name' => 'Tangwani'],
            ['state_id' => 8,'name' => 'Tharu Shah'],
            ['state_id' => 8,'name' => 'Thatta'],
            ['state_id' => 8,'name' => 'Thul'],
            ['state_id' => 8,'name' => 'Ubauro'],
            ['state_id' => 8,'name' => 'Umarkot'],
            ['state_id' => 8,'name' => 'Umerkot District'],
            ['state_id' => 8,'name' => 'Warah'],
        ];
        foreach ($ciies as $key => $value) {
            City::create($value);
        }
    }
}
