<?php

namespace Database\Seeders;

use App\Models\Service;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ServiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $services = [
            ['category_id' => 1,'service' =>'YouTube - Subscribers ~ 100-150/days PKR 3500 per 1000','rate' =>3500,'min_value' =>50 ,'max_value' => 40000,'avg_time' =>10080,"description" =>"🔗 Accurate Channel Handle or Link: Paste your channel handle or link correctly while placing the order. 🚫 Avoid Handle Changes: Ensure your channel handle remains unchanged; altering it will result in order cancellation. 🎥 Long Video Requirement: Your channel should feature a video lasting between 01:00 to 01:30 minutes. ⏳ Possible Order Delays: Occasionally, orders might experience delays due to server load.",'start_time_from' =>20,'start_time_to' =>50 ,'speed_from' =>100,'speed_to' =>150,'category_id'=>1],

            ['category_id' => 1,'service' =>'YouTube - Views ~ 1K-3K/days PKR 550 per 1000','rate' =>550,'min_value' =>1000 ,'max_value' => 50000,'avg_time' =>1440,"description" =>"⚠ Important Notes: 📌 Please review the link format thoroughly prior to confirming your order. 🔓 Ensure your account settings are set to public, not private. 📌 During peak periods, the initial speed of the operation may vary. 📌 Avoid placing a second order on the same link until your current order is processed in the system.",'start_time_from' =>30,'start_time_to' =>50 ,'speed_from' =>1000,'speed_to' =>3000,'category_id'=>1],

            ['category_id' => 1,'service' =>'YouTube - Watchtime ~ 2K-3K/days PKR 1050 per 1000','rate' =>1050,'min_value' =>1000 ,'max_value' => 4000,'avg_time' =>5760,"description" =>"🕒 Complete Your YouTube Channel Watch Time: Ensure your channel meets the required watch time. 🎬 Video Quantity and Duration: Have 5 to 6 videos posted, each lasting between 4 to 8 minutes. 🔗 Accurate Link Pasting: Precisely paste the links for successful order processing. ⚠️ Server Overload Caution: Occasionally, server overload might cause delays in the process.",'start_time_from' =>2880,'start_time_to' =>7200,'speed_from' =>2000,'speed_to' =>3000,'guarranty'=>7 ,'category_id'=>1],

            ['category_id' => 1,'service' =>'YouTube - Comments ~ 20-50/days PKR 2400 per 100','rate' =>24000,'min_value' =>10 ,'max_value' => 1000,'avg_time' =>14400,"description" =>"🔗 Check the Video Link: Make sure you paste the right video link to avoid any issues. 💬 Authentic Comments: We provide genuine comments that truly improve your content. 👁️ Public Video: Keep your video public so we can work on it smoothly. ⏳ Possible Delays: Sometimes, there might be slight delays in the number of comments due to our dedication to quality work.",'start_time_from' =>30,'start_time_to' =>50 ,'speed_from' =>20,'speed_to' =>50,'category_id'=>1],

            ['category_id' => 1,'service' =>'YouTube - Real Ads Views ~ 10K-30K/days PKR 2050','rate' =>2050,'min_value' =>1000 ,'max_value' => 100000,'avg_time' =>4320,"description" =>"👀 Real YouTube Ad Views: Get genuine views for your video ads now! 🔗 Accurate Video Link: Paste your video link correctly for immediate activation, or wait for active ads within 24 to 48 hours. 💯 Authentic Audience: Experience 100% real views from a niche-specific audience, ensuring authenticity within your channel's category.",'start_time_from' =>1440,'start_time_to' =>2880,'speed_from' =>10000,'speed_to' =>30000,'category_id'=>1],

            ['category_id' => 1,'service' =>'YouTube - Likes ~ 5K-10K/days PKR 250 per 1000','rate' =>250,'min_value' =>50,'max_value' =>100000,'avg_time' =>2100,"description" =>"👍 Enhance Your YouTube Likes: Improve your video with additional likes now! 🔗 Accurate Video Link: Provide the correct video link for timely likes delivery. 📌 Single Order Request: Kindly place only one order per link until the current one is processed in the system.",'start_time_from' =>30,'start_time_to' =>50 ,'speed_from' =>5000,'speed_to' =>10000,'category_id'=>1],

            ['category_id' => 2,'service' =>'Instagram - Followers ~ 5K-20K/days PKR 290 per 1000','rate' =>290,'min_value' =>1000 ,'max_value' => 1000000,'avg_time' =>360,"description" =>"👥 Increase Your Instagram Followers: Grow your follower count now! 🔗 Accurate Profile Link: Provide the correct profile link for follower delivery. 📌 Single Order Request: Please place only one order at a time until the current one is processed in the system.",'start_time_from' =>120,'start_time_to' =>300,'speed_from' =>5000,'speed_to' =>20000,'category_id'=>2],

            ['category_id' => 2,'service' =>'Instagram - Views ~ Video/Reels/TV~ 1K-20K/days PKR 90 per 1000','rate' =>90,'min_value' =>1000 ,'max_value' => 1000000,'avg_time' =>30 ,"description" =>"👀 Increase Your Instagram Views: Enhance your video with more views now! 🔗 Accurate Post Link: Provide the correct post link for timely views delivery. 📌 Single Order Request: Kindly place only one order per link until the current one is processed in the system.",'start_time_from' =>10,'start_time_to' =>30 ,'speed_from' =>1000,'speed_to' =>20000,'category_id'=>2],

            ['category_id' => 2,'service' =>'Instagram - Likes ~ 5K-20K/days PKR 115 per 1000','rate' =>115,'min_value' =>200 ,'max_value' => 1000000,'avg_time' =>30,"description" =>"❤️ Boost Your Instagram Likes: Increase your likes now! 🔗 Accurate Post Link: Share the correct post link for prompt likes delivery. 📌 Single Order Request: Kindly avoid placing multiple orders for the same link until the current order is processed in the system.",'start_time_from' =>10,'start_time_to' =>30 ,'speed_from' =>5000,'speed_to' =>20000,'category_id'=>2],

            ['category_id' => 2,'service' =>'Instagram - Comments ~ 20-50/days PKR 2400 per 100','rate' =>24000,'min_value' =>10 ,'max_value' => 1000,'avg_time' =>14400,"description" =>"💬 Authentic Interaction: Enhance your posts with additional comments from real users! 🔗 Accurate Post Link: Provide the correct post link for timely comment delivery. ⏳ Possible Delays: Please note that orders might take some time due to the authentic engagement from real individuals. 📌 Single Order Reminder: Please avoid placing a second order for the same post until the current order is processed in the system.",'start_time_from' =>30,'start_time_to' =>50 ,'speed_from' =>20,'speed_to' =>50,'category_id'=>2],

            ['category_id' => 3,'service' =>'Facebook - Page Followers Real Ads ~ 5K-10K/days PKR 750 per 1000','rate' =>750,'min_value' =>1000 ,'max_value' => 1000000,'avg_time' =>1440,"description" =>"👥 Genuine Facebook Page Followers: Grow your page with real followers now! 🔗 Grant Page Access: To expedite the process, provide access to your page. After placing the order, copy the order ID and contact our support team for any queries or to grant necessary access. 📈 Promote Your Page: Gain followers and enhance your page's visibility through targeted advertising strategies.",'start_time_from' =>300,'start_time_to' =>360,'speed_from' =>5000,'speed_to' =>10000,'category_id'=>3],

            ['category_id' => 3,'service' =>'Facebook - Views ~ Video/Reels ~ 1K-20K/days PKR 100 per 1000','rate' =>100,'min_value' =>1000 ,'max_value' => 500000,'avg_time' =>1080,"description" =>"👁️ Boost Your Video Views: Increase your video's visibility now! 🔗 Accurate Video Link: Provide the correct video link for prompt view delivery. ⏳ Possible Delays: Orders may experience delays due to processing. 📌 Single Order Reminder: Please avoid placing a second order for the same video until the current order is processed in the system. 🔓 Public Video Note: Ensure your video is set to public for smooth processing. Avoid setting it to private.",'start_time_from' =>10,'start_time_to' =>30 ,'speed_from' =>1000,'speed_to' =>20000,'category_id'=>3],

            ['category_id' => 3,'service' =>'Facebook - Watchtime ~ 10K-60K/days PKR 100 per 1000','rate' =>100,'min_value' =>60000 ,'max_value' => 180000,'avg_time' =>7200,"description" =>"🔗 Accurate Video Link: Paste your video link correctly when placing the order. 🚫 Avoid Link Changes: Ensure your video link remains unchanged; any alterations may result in a canceled order. 🎥 Long Video Requirement: Your video should have a duration between 1 to 2 hours for optimal watch time. ⏳ Possible Order Delays: Please note, there might be delays occasionally due to server load.",'start_time_from' =>1440,'start_time_to' =>2880,'speed_from' =>10000,'speed_to' =>60000,'guarranty'=>60 ,'category_id'=>3],

            ['category_id' => 3,'service' =>'Facebook - Post Likes ~ 1K-2K/days PKR 250 per 1000','rate' =>250,'min_value' =>100 ,'max_value' => 10000,'avg_time' =>2160,"description" =>"👍 Increase Your Facebook Likes: Elevate your likes now! 🔗 Accurate Post Link: Share the correct post link for prompt likes delivery. 📌 Single Order Request: Kindly avoid placing multiple orders for the same link until the current order is processed in the system. 🔓 Public Post Note: Ensure your Facebook post is set to public for effective processing. Avoid setting it to private.",'start_time_from' =>1440,'start_time_to' =>2880,'speed_from' =>1000,'speed_to' =>2000,'category_id'=>3],

            ['category_id' => 3,'service' =>'Facebook - Comments ~ 20-50/days PKR 1750 per 1000','rate' =>17500,'min_value' =>10 ,'max_value' => 1000,'avg_time' =>12960,"description" =>"💬 Genuine Engagement: Elevate your posts with additional comments from real users! 🔗 Accurate Post Link: Provide the correct post link for timely comment delivery. ⏳ Possible Delays: Please note that orders might take some time due to the authentic engagement from real individuals. 📌 Single Order Reminder: Please avoid placing a second order for the same post until the current order is processed in the system.",'start_time_from' =>30,'start_time_to' =>50 ,'speed_from' =>20,'speed_to' =>50,'category_id'=>3],

            ['category_id' => 3,'service' =>'Facebook - Real Ads Views ~ 5K-10K/days PKR 2050 per 1000','rate' =>2050,'min_value' =>1000 ,'max_value' => 1000000,'avg_time' =>1440,"description" =>"👀 Genuine Facebook Ad Views: Experience real views for your video ads now! 🔗 Provide Page Access: To ensure prompt activation, grant access to your page. After placing the order, copy the order ID and contact our support team with any questions. 💯 Authentic Audience: Receive authentic views from a targeted audience, ensuring relevance within your page's category.",'start_time_from' =>1440,'start_time_to' =>2880,'speed_from' =>5000,'speed_to' =>10000,'category_id'=>3],

            ['category_id' => 3,'service' =>'Facebook - Ads Boosting ~ Reach 3K-4K/days PKR 3500 per 4 days','rate' =>3500,'min_value' =>4 ,'max_value' => 120,'avg_time' =>5760,"description" =>"🎯 Facebook Ad Boosting: Reach 3K-4K people for PKR 3500 over 4 days! 📝 Contact Support: After placing the order, copy the order ID and contact our support team. You'll need to provide your WhatsApp number for clients conversation",'start_time_from' =>300,'start_time_to' =>360,'speed_from' =>3000,'speed_to' =>4000,'category_id'=>3],

            ['category_id' => 3,'service' =>'Facebook - Page Reviews ~ 30-100/days PKR 2200 per 100','rate' =>22000,'min_value' =>30 ,'max_value' => 1000,'avg_time' =>14400,"description" =>"🌟 Genuine Facebook Page Reviews: Enhance your page with authentic reviews! 🔗 Accurate Page Link: Share your page link for authentic review delivery. 📌 Single Order Reminder: Kindly avoid placing multiple orders for the same link until the current order is processed in the system.",'start_time_from' =>30,'start_time_to' =>50 ,'speed_from' =>30,'speed_to' =>100,'category_id'=>3],

            ['category_id' => 4,'service' =>'TikTok - Followers Real User ~ 5K-10K/days PKR 1800 per 1000','rate' =>1800,'min_value' =>1000 ,'max_value' => 100000,'avg_time' =>840,"description" =>"👥 TikTok Ads for Genuine Followers: Get real followers through TikTok ads! 📝 Provide Video Code: Share your TikTok video code for follower acquisition. 🔍 Authentic Engagement:",'start_time_from' =>120,'start_time_to' =>180,'speed_from' =>5000,'speed_to' =>10000,'category_id'=>4],

            ['category_id' => 4,'service' =>'TikTok - Views Real User ~ 5K-10K/days PKR 1500 per 1000','rate' =>1500,'min_value' =>1000 ,'max_value' => 100000,'avg_time' =>360,"description" =>"👁️ TikTok Ads for Views: Increase your TikTok video views! 📝 Provide Video Code: Share your TikTok video code for view enhancement. 🔍 Authentic Engagement: These views are generated through TikTok ads, ensuring genuine and real user engagement.",'start_time_from' =>120,'start_time_to' =>180,'speed_from' =>5000,'speed_to' =>10000,'category_id'=>4],

            ['category_id' => 4,'service' =>'TikTok - Likes Real User ~ 5K-10K/days PKR 1700 per 1000','rate' =>1700,'min_value' =>1000 ,'max_value' => 100000,'avg_time' =>360,"description" =>"👁️ TikTok Ads for Views: Boost your TikTok video views! 📝 Share Video Code: Provide your TikTok video code to enhance your views. 🔍 Genuine Engagement: These views are obtained through TikTok ads, ensuring genuine and real user engagement.",'start_time_from' =>120,'start_time_to' =>180,'speed_from' =>5000,'speed_to' =>10000,'category_id'=>4],

            ['category_id' => 4,'service' =>'TikTok - Shares Real User ~ 1K-3K/days PKR 1800 per 1000','rate' =>1800,'min_value' =>1000 ,'max_value' => 10000,'avg_time' =>1440,"description" =>"🔗 TikTok Video Shares: Increase your video's visibility! 📎 Share Video Link: Provide the link to your TikTok video for sharing. 👥 Genuine Shares: Your video will be shared by real users, enhancing its reach organically.",'start_time_from' =>300,'start_time_to' =>360,'speed_from' =>1000,'speed_to' =>3000,'category_id'=>4],
        ];
        foreach($services as $data){
            Service::create($data);
        }
    }
}
